insert into owners values(1, 'Prerak Semwal', 'prerak20105@iiitd.ac.in', '@edve$%#Dgsgsd', '9234567899');
insert into owners values(2, 'Vineet Kaul', 'vineet20153@iiitd.ac.in', 'sdfs$#etjdg1R', '9876543222');
insert into owners values(3, 'Janhavi Bayanwar', 'bayanwar20043@iiitd.ac.in', '^yrHa!643DFGsdf', '9231231235');
insert into owners values(4, 'Abhinav Kumar Sinha', 'abhinav20012@iiitd.ac.in', 'werwr$%#@46422', '9545767691');	

insert into items (item_id, item_name, cost_price, selling_price, quantity, item_type) values (1, 'apple', 0.37, 0.40, 500, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('banana',0.053, 0.066, 165, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('pear', 0.28, 0.33, 260, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('figs',0.092 , 0.13, 120, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('onion',0.079 , 0.092, 100, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('strawberry',0.066 , 0.092, 370, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('pineapple',0.59 , 0.66, 410, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('watermelon',0.92 , 0.99, 115, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('pomegranate',0.53 , 0.61, 245, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('muskmelon',0.78 , 0.79, 655, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('guava',0.11 , 0.13, 334, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('orange',0.26 , 0.29, 470, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('potato',0.040,  0.053, 950, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('cauliflower',0.62 , 0.66, 427, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('corn',0.20 , 0.21, 612, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('pumpkin',1.02 , 1.06, 429, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('papaya',0.58 , 0.59, 189, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('cabbage',0.91 , 0.92, 350, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('coconut',0.16 , 0.20, 600, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('broccoli',0.40, 0.46, 150, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('tomato',0.026 , 0.066, 800, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('ginger',0.092 , 0.13, 100, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('lemon',0.066 , 0.092, 100, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('kiwi',0.34 , 0.40, 170, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('coriander',0.053 , 0.066, 530, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('spinach',0.040 , 0.092, 420, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('lettuce',0.28 , 0.33, 330, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('mint',0.066 , 0.079, 260, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('cucumber',0.053 , 0.066, 320, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('garlic',0.26 , 0.36, 800, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('brinjal',0.13 , 0.15, 600, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('grapes',0.48 , 0.49, 770, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('chikoo',0.026, 0.066, 500, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('fenugreek',0.11 , 0.16, 360, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('avocado',1.58 , 1.72, 130, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('olive oil', 5,9 , 20, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('canned milk', 0.94, 1.38, 32, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('brown sugar', 2, 4.7 , 29, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('sugar', 1.54 , 4, 55, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('instant noodles', 2 , 4, 57, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('cherries', 2.54, 3.66 , 100, 'Grocery');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('mobile',120 , 200, 700, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('air conditioner',450 , 550, 150, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('television',280 ,390 , 100, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('beard trimmer',50 ,69 , 200, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('Body trimmer',12 ,19 , 200, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('LED bulb',3 ,5 , 200, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('extension cord',4 ,6 , 70, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('earphones', 7 ,9 , 500, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('power bank', 18 ,24 , 300, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('wifi router', 38 ,60 , 100, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('wrist watch', 70 ,99 , 700, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('wall clock', 45 ,70 , 200, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('fitbit', 55 ,70 , 1000, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('headphones', 180 ,279 , 400, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('apple air pods', 100 ,200 , 300, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('laptop', 350 ,460 , 250, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('gaming mouse', 27 ,42 , 500, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('keyboard', 15 ,28 , 400, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('table lamp', 9, 15 , 100, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('flashlight', 9, 17 , 230, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('electrical toothbrush', 22, 39 , 100, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('washing Machine', 230, 312 , 158, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('refrigerator', 180, 240 , 125, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('air purifier', 100, 150 , 88, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('toaster', 25, 40 , 75, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('hair straightener', 25, 40 , 100, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('blender', 40, 65 , 134, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('inverter battery', 90, 140 , 100, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('projector', 1500, 2000 , 50, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('microwave', 50, 70 , 100, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('iron',20 , 30, 40, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('heater', 29,32 , 52, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('microphone', 10,15 , 33, 'Electronics');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('tooth-paste',7 ,9 , 1000,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('tooth-brush',9 ,15 ,1500 ,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('diapers',50 ,60 , 700,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('facewash',11 ,15 , 300,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('perfume',40 ,45 , 169,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('soap', 1,2 , 900,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('hairspray',16 ,20 , 120,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('hair shampoo',6 ,9 , 210,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('dental floss',7 ,10 , 113,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('face mask',4 ,6 , 3000,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('sanitizer',8 ,14 , 1000,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('liquid handwash',3 ,5 , 234,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('lotion',6 ,8 , 199,'Daily care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('nail clippers',5 ,7 , 78,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('moisturizer',20 ,27 , 200,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('foundation',15 ,20 , 60,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('mosquito repellent',3 ,4 , 100,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('body wash',8 ,10 , 122,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('disinfectant liquid',10 ,15 , 50,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('disinfectant spray',11 ,14 , 77,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('lipstick',5 ,7 , 100,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('eyeliner',6 ,7 , 88,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('mascara',9 ,12 , 54,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('nail polish remover',16 ,24 , 90,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('nail polish',20 ,30 , 179,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('eye lubricant',7 ,10 , 50,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('sunscreen lotion',4 ,5 , 69,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('hair serum',22 ,35 , 99,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('hair oil',7 ,8 ,90 ,'Daily Care');
insert into items (item_name, cost_price, selling_price, quantity, item_type) values ('tooth picks',2 ,3 ,150 ,'Daily Care');








insert into support (support_id, customer_id, issue,issue_date) values(1, 269, 'Ihe colour of phone does not match with the one I ordered', '2021-10-10');
insert into support (customer_id, issue, issue_date) values( 450, 'I am not able to add products to my cart', '2022-11-12');
insert into support (customer_id, issue, issue_date) values( 73, 'The iron I ordered is not heating up properly', '2022-01-27');
insert into support (customer_id, issue, issue_date) values( 90, 'The lid of the blender was broken', '2022-02-19');
insert into support (customer_id, issue, issue_date) values( 90, 'The lid of the blender was broken', '2022-02-27');
insert into support (customer_id, issue, issue_date) values( 123, 'Laptop is not turning on', '2022-02-25');
insert into support (customer_id, issue, issue_date) values( 234, 'Earphone not working', '2022-02-23');
insert into support (customer_id, issue, issue_date) values( 345, 'I am not able to place order', '2022-02-23');
insert into support (customer_id, issue, issue_date) values( 456, 'I have not recieved my order which was meant to be delivered yesterday', '2022-02-27');
insert into support (customer_id, issue, issue_date) values( 678, 'Wrong item was sent', '2022-02-25');
insert into support (customer_id, issue, issue_date) values( 890, 'Quality not adequate', '2022-02-18');
insert into support (customer_id, issue, issue_date) values( 901, 'The packaging of the product was already opened.', '2022-02-15');
insert into support (customer_id, issue, issue_date) values( 433, 'Unavailable or out of stock product', '2022-02-10');
insert into support (customer_id, issue, issue_date) values( 167, 'Money not refunded', '2022-02-5');
insert into support (customer_id, issue, issue_date) values( 298, 'The toothpaste was expired', '2022-01-26');
insert into support (customer_id, issue, issue_date) values( 888, 'Billing Issues', '2022-01-23');
insert into support (customer_id, issue, issue_date) values( 40, 'The fruits were not fresh', '2022-01-20');
insert into support (customer_id, issue, issue_date) values( 567, 'I am unable to avail the displayed offer', '2022-01-19');
insert into support (customer_id, issue, issue_date) values( 786, 'The lid of the blender was broken', '2022-01-19');
insert into support (customer_id, issue, issue_date) values( 99, 'I am unable to avail the displayed offer', '2022-01-13');
insert into support (customer_id, issue, issue_date) values( 200, 'Unavailable or out of stock product', '2022-01-13');
insert into support (customer_id, issue, issue_date) values( 100, 'I am unable to avail the displayed offer', '2022-01-10');
insert into support (customer_id, issue, issue_date) values( 300, 'unable to log in on the app', '2022-01-10');
insert into support (customer_id, issue, issue_date) values( 444, 'Prices Are Too High', '2020-01-10');

insert into feedback values(23, 4);
insert into feedback values(1, 5);
insert into feedback values(44, 3);
insert into feedback values(3, 5);
insert into feedback values(66, 4);
insert into feedback values(90, 3);
insert into feedback values(46, 2);
insert into feedback values(780, 4);
insert into feedback values(555, 4);
insert into feedback values(333, 5);
insert into feedback values(900, 3);
insert into feedback values(69, 3);
insert into feedback values(96, 4);
insert into feedback values(67, 2);
insert into feedback values(420, 4);
insert into feedback values(619, 4);
insert into feedback values(123, 3);
insert into feedback values(234, 3);
insert into feedback values(771, 3);
insert into feedback values(212, 5);
insert into feedback values(153, 5);
insert into feedback values(105, 5);
insert into feedback values(89, 3);
insert into feedback values(50, 3);
insert into feedback values(850, 4);
insert into feedback values(700, 4);
insert into feedback values(403, 3);
insert into feedback values(543, 5);
insert into feedback values(137, 4);
insert into feedback values(810, 4);
insert into feedback values(654, 2);
insert into feedback values(383, 4);
insert into feedback values(504, 4);
insert into feedback values(77, 4);
insert into feedback values(199, 5);
insert into feedback values(200, 5);
insert into feedback values(299, 2);
insert into feedback values(399, 3);
insert into feedback values(666, 3);
insert into feedback values(786, 5);
insert into feedback values(903, 5);

insert into payments(payment_id, customer_id, mode, amount) values (1, 2, 'NetBanking', 100);
insert into payments(customer_id, mode, amount) values (2, 'NetBanking', 37.4);
insert into payments(customer_id, mode, amount) values (7, 'NetBanking', 24.472);
insert into payments(customer_id, mode, amount) values (18, 'NetBanking', 34);
insert into payments(customer_id, mode, amount) values (19, 'NetBanking', 26);
insert into payments(customer_id, mode, amount) values (3, 'NetBanking', 55);
insert into payments(customer_id, mode, amount) values (6, 'NetBanking', 40);
insert into payments(customer_id, mode, amount) values (17, 'NetBanking', 55);
insert into payments(customer_id, mode, amount) values (7, 'NetBanking', 200);
insert into payments(customer_id, mode, amount) values (4, 'NetBanking', 100);
insert into payments(customer_id, mode, amount) values (3, 'UPI', 70);
insert into payments(customer_id, mode, amount) values (5, 'UPI', 140);
insert into payments(customer_id, mode, amount) values (2, 'UPI', 500);
insert into payments(customer_id, mode, amount) values (13, 'UPI', 500);
insert into payments(customer_id, mode, amount) values (15, 'UPI', 200);
insert into payments(customer_id, mode, amount) values (20, 'UPI', 49.68);
insert into payments(customer_id, mode, amount) values (11, 'UPI', 237);
insert into payments(customer_id, mode, amount) values (17, 'UPI', 314.96);
insert into payments(customer_id, mode, amount) values (11, 'UPI', 300);
insert into payments(customer_id, mode, amount) values (11, 'UPI', 140);
insert into payments(customer_id, mode, amount) values (12, 'UPI', 314.96);
insert into payments(customer_id, mode, amount) values (6, 'Credit-Card', 212);
insert into payments(customer_id, mode, amount) values (17, 'Credit-Card', 164.83);
insert into payments(customer_id, mode, amount) values (9, 'Credit-Card', 59.59);
insert into payments(customer_id, mode, amount) values (9, 'Credit-Card', 29.92);
insert into payments(customer_id, mode, amount) values (10, 'Credit-Card', 1200);
insert into payments(customer_id, mode, amount) values (10, 'Credit-Card', 9000);
insert into payments(customer_id, mode, amount) values (9, 'Credit-Card', 900);
insert into payments(customer_id, mode, amount) values (4, 'Credit-Card', 900);
insert into payments(customer_id, mode, amount) values (1, 'Credit-Card', 1800);
insert into payments(customer_id, mode, amount) values (8, 'Debit-Card', 300);
insert into payments(customer_id, mode, amount) values (17, 'Debit-Card', 400);
insert into payments(customer_id, mode, amount) values (8, 'Debit-Card', 90);
insert into payments(customer_id, mode, amount) values (19, 'Debit-Card', 700);
insert into payments(customer_id, mode, amount) values (4, 'Debit-Card', 62.62);
insert into payments(customer_id, mode, amount) values (4, 'Debit-Card', 900);
insert into payments(customer_id, mode, amount) values (5, 'Debit-Card', 70);
insert into payments(customer_id, mode, amount) values (15, 'Debit-Card', 1000);
insert into payments(customer_id, mode, amount) values (5, 'Debit-Card', 500);
insert into payments(customer_id, mode, amount) values (16, 'Debit-Card', 400);
